### ISSUE TITLE
gpg error

### ISSUE THREAD

**Issue by mac-linux-free** [torvic9/linux413-vd#1]
hi torvic,

here is an error

linux-4.13.tar ... Durchgelaufen
    linux-hardened-4.13.2.a.patch ... FEHLGESCHLAGEN (Unbekannter öffentlicher Schlüssel F9E712E59AF5F22A)

**Comment by torvic9** [comment]
Did you import Daniel Micay's public key?
Note: I haven't compiled this kernel yet.

**Comment by torvic9** [comment]
That's not a fix. It works here.
